# confluence/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: confluence
type: Opaque
data:
  password: Y29uZmx1ZW5jZXBhc3M= # base64 encoded "confluencepass"

---
apiVersion: v1
kind: Secret
metadata:
  name: confluence-secret
  namespace: confluence
type: Opaque
data:
  license: "QUFBQTlBME9EQW9QZU5wZGowRlB3a0FRaGUvN0t6YnhabExTWFRFR2tqMkFiWUJvU3hPMlNyaU5kY0NOWmRyTWJxdjhlNUhxaGVQN1gKdWJMdkp1c0laa0JTeldSU2szVnd6UWV5eUt4VXNkS2l3Ujl4YTROcmlGajBRZFp1d3JKbzl3M0xOdTZPemlTNzloajNiVElYdVRkOApRMTV2Uy85T1JrVmkwZEcrRDFPSUtEUlN1a28xcEcrRjJrUGRYZHBUT0FPeGFEeW85c1JWTUgxT05BTUhBVWtvQXJUNzlieDZhSXA3CnBaaXpRY2c1d2ZETE5UZ3ZRTVNHK1FlZVpXWStXSmlvMjM1TW82ZWRydGxOSS9WcTNnZVhqKzNKWDFTODBYLzVNcjlSKzJweFJ5T2EKR3k2c2F0OElZcU9xdy93ZUwzbEI3eklhOHN3TEFJVUxVL0JseVpvT1ZiTFBFVkdBVkFpbzlZaDN0NENGRkJKSmQwMGZMbmtremdleApWK1Q2TnNpUFZwZ1gwMmNrCg==" 
# Add your Confluence license key here (base64 encoded)
