# argo-app/confluence-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: confluence
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/confluence-k8s # Replace with your Git repository
    targetRevision: HEAD
    path: confluence
  destination:
    server: https://kubernetes.default.svc
    namespace: confluence
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Validate=false

